export const drinksData = [
  {
    title: "Orange Juice",
    price: 4.5,
    src: "/assets/juices/orange-juice/orange-juice-128w.jpeg",
    width: 128,
    height: 128,
    alt: "A picture of an orange juice",
    description: "Fresh oranges.",
  },
  {
    title: "Pineapple Juice",
    price: 5.0,
    src: "/assets/juices/pineapple-juice/pineapple-juice-128w.jpeg",
    width: 128,
    height: 128,
    alt: "A picture of an pineapple juice",
    description: "Ripe pineapple.",
  },
  {
    title: "Green Juice",
    price: 6.0,
    src: "/assets/juices/green-juice/green-juice-128w.jpeg",
    width: 128,
    height: 128,
    alt: "A photo of a green juice made with kale, apple and lemon",
    description: "Kale, apple, lemon, water.",
  },
  {
    title: "Mango Juice",
    price: 4.5,
    src: "/assets/juices/sleeve-juice/sleeve-juice-128w.jpeg",
    width: 128,
    height: 128,
    alt: "A picture of an mango juice",
    description: "Ripe mango, water, sugar.",
  },
  {
    title: "Watermelon Juice",
    price: 4.0,
    src: "/assets/juices/watermelon-juice/watermelon-juice-128w.jpeg",
    width: 128,
    height: 128,
    alt: "A picture of an watermelon juice",
    description: "Watermelon, lemon.",
  },
]